# netlify.toml
[build]
  command = "next build && next export"
  publish = "out"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../../"

[dev]
framework = "#static"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
